name: juju-backup-all
base: core20
adopt-info: juju-backup-all
summary: Tool for backing up charms, local configs, and Juju controllers.
description: |
  Juju-backup-all allows operators to perform backups across all controllers
  and models. It provides autodiscovery, backing up all applications of supported
  charms. The tool also includes options to exclude charms, select which
  controllers to backup, and backup local configs.

  Supported charms: mysql-innodb-cluster, etcd, postgresql

  Supported config backups: Juju
issues: https://bugs.launchpad.net/juju-backup-all
source-code: https://git.launchpad.net/juju-backup-all
website: https://launchpad.net/juju-backup-all
license: Apache-2.0
confinement: strict

apps:
  juju-backup-all:
    command: bin/juju-backup-all
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
      PYTHONPATH: $PYTHONPATH:$SNAP/lib/python3.8/site-packages
    plugs:
      - network
      - home
      - juju-client-observe
      - ssh-keys

parts:
  juju-backup-all:
    plugin: python
    python-packages:
      - .
    source: .
    source-type: git
    override-build: |
      snapcraftctl build
      echo "Version: $(python3 setup.py --version)"
      snapcraftctl set-version "$(python3 setup.py --version)"
    stage-packages:
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3.8-minimal
      - openssh-client
